// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogylsucfcymimnlxxtmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9neWxzdWNmY3ltaW1ubHh4dG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDU3NjksImV4cCI6MjA1ODIyMTc2OX0.rwrvfc6vduDNev87t41kZ8mMEt0T-SsrdRZCE1FI2HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);